// import './products-slider-click';
import './header-menu';
import './buy-now-modal';
import './modal';
import './slider';
import './review-modal-form';
import './open-modal';
import './tel-modal';
import './how-made-video';
// import './buy-now-slider';
import './scroll';